[package]
name = "gun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = {version = "0.29.2", features = ["base64"] }
bitcoincore-rpc = "0.16.0"
hex = "0.4.3"
ripemd = "0.1.3"
sha2 = "0.10.6"
